# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


# Disable the AWS module
[aws]
disabled = true

[git_branch]
symbol = "ğŸ™ "

[git_commit]
disabled = false

[git_status]
disabled = false

[nodejs]
symbol = "ğŸŒ± "
